version: '2'
services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - docker-postgres:/var/lib/postgresql/data
  web:
    build: .
    env_file: .env
    command: rails s -p ${RAILS_PORT} -b 0.0.0.0
    volumes:
      - .:/transfer
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    depends_on:
      - db
    links:
      - db

volumes:
  docker-postgres:
