# Group Чанки
## Чанки [/materials/{material_id}/chunks]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала

### Список чанков [GET]

+ Response 200 (application/json)

    + Attributes (array[Chunk])

### Создать слайс [POST]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на создание чанков
:::

Атрибут | Тип | Описание
--- | --- | ---
material_position | Integer | Позиция чанка в материале.
type_id | Integer | Идентификатор типа чанка.
translatable | boolean | Чанк переводимый? Пример непереводимого чанка — иллюстрация без текста.
body | String | Оригинальное значение чанка, в случае если значение нетекстовое (изображение, аудиозапись), то размещается ссылка на объект

+ Request (application/json)

    + Attributes (object)
        + material_position: 0 (number) - Позиция чанка в материале
        + chunk_type_id: 1 (number) - Тип чанка
        + translatable: true (boolean) - Чанк переводимый? Пример непереводимого чанка - иллюстрация без текста
        + body: Hey bro! (string) - Оригинальное значение чанка, в случае если значение нетекстовое (изображение, аудиозапись), то размещается ссылка на объект

+ Response 201 (application/json)

    + Attributes (Chunk)

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Field 'body' is required."
                }
            ]
        }

## Чанк [/materials/{material_id}/chunks/{chunk_id}]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала
    + chunk_id: 2 (required, number) - идентификатор чанка

### Получить слайс [GET]

+ Response 200 (application/json)

    + Attributes (Chunk)

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Material was not found."
                }
            ]
        }

### Редактировать слайс [PUT]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на редактирование чанков
:::

::: note
#### Обработка параметров на сервере
Все указанные в запросе аттрибуты полностью заменяют соответствующие аттрибуты
в базе данных.
:::

+ Request (application/json)

+ Attributes (object)
    + material_position: 0 (number) - Позиция чанка в материале
    + chunk_type_id: 1 (number) - Тип чанка
    + translatable: true (boolean) - Чанк переводимый? Пример непереводимого чанка - иллюстрация без текста
    + body: Hey bro! (string) - Оригинальное значение чанка, в случае если значение нетекстовое (изображение, аудиозапись), то размещается ссылка на объект

+ Response 200 (application/json)

    + Attributes (Chunk)

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Field 'body' is required."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Chunk was not found."
                }
            ]
        }

### Удалить слайс [DELETE]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на удаление чанков
:::

+ Response 200 (application/json)

+ Response 401 (application/json)

        {
            "errors": [
                {
                    "title": "Unauthorized access.",
                    "detail": "You don't have rights to delete slice."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Chunk was not found."
                }
            ]
        }

## Комментарии [/materials/{material_id}/chunks/{chunk_id}/comments]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала
    + chunk_id: 2 (required, number) - идентификатор чанка

### Список комментариев [GET]

+ Response 200 (application/json)

    + Attributes (array[Comment])

### Создать комментарий [POST]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на создание комментариев
:::

Атрибут | Тип | Описание
--- | --- | ---
body | String | Текст комментария.

+ Request (application/json)

    + Attributes (object)
        + body (string) - Текст комментария

+ Response 201 (application/json)

    + Attributes (Comment)

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Material should exist."
                }
            ]
        }

+ Response 401 (application/json)

        {
            "errors": [
                {
                    "title": "Unauthorized access.",
                    "detail": "You don't have rights to comment this slice."
                }
            ]
        }

## Комментарий [/materials/{material_id}/chunks/{chunk_id}/comments/{comment_id}]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала
    + chunk_id: 2 (required, number) - идентификатор чанка
    + comment_id: 10 (required, number) - идентификатор комментария

### Получить комментарий [GET]

+ Response 200 (application/json)

    + Attributes (Comment)

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Comment was not found."
                }
            ]
        }

### Редактировать комментарий [PUT]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на редактирование комментариев
:::

+ Request (application/json)

    + Attributes (object)
        + body (string) - Текст комментария
        + parent_id (number) - Идентификатор родительского комментария

+ Response 200 (application/json)

    + Attributes (Comment)

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Material should exist."
                }
            ]
        }

+ Response 401 (application/json)

        {
            "errors": [
                {
                    "title": "Unauthorized access.",
                    "detail": "You don't have rights to edit this comment."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Comment was not found."
                }
            ]
        }

### Удалить комментарий [DELETE]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на удаление комментариев
:::

+ Response 204 (application/json)

+ Response 401 (application/json)

        {
            "errors": [
                {
                    "title": "Unauthorized access.",
                    "detail": "You don't have rights to delete this comment."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Comment was not found."
                }
            ]
        }
