FORMAT: 1A

# Junkyard API v1.4.0

API для организации работы над оригинальными материалами, включая перевод
и редактирование.

<!-- include(data_types.apib) -->
<!-- include(materials.apib) -->
<!-- include(slices.apib) -->
<!-- include(translations.apib) -->
