# Group Варианты переводов чанков
::: note
У каждого *переводимого* **чанка** может быть несколько **вариантов перевода**
от нескольких переводчиков. У каждого **варианта перевода** есть свой **рейтинг**
выставляемый другими переводчиками, редакторами и прочими участниками проекта.
:::

## Варианты переводов [/materials/{material_id}/chunks/{chunk_id}/translations]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала
    + chunk_id: 8712 (required, number) - идентификатор чанка

### Список вариантов переводов [GET]

+ Response 200 (application/json)

    + Attributes
        + data(array, fixed-type)
            + (Translation)
                + rates
                    + data (array, fixed-type)
                        + (Rate)

### Создание варианта перевода [POST]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на создание вариантов перевода
:::

Атрибут | Тип | Описание
--- | --- | ---
body | String | Значение варианта перевода

+ Request (application/json)

    + Attributes (object)
        + body: Хей бро! (required, string) - Перевод чанка

+ Response 201 (application/json)

    + Attributes (object)
        + id: 987 (required, number) - Уникальный идентификатор варианта перевода
        + translator (required, User) - Автор (пользователь портала) варианта перевода
        + body: Хей бро! (required, string) - Перевод чанка
        + rating: 0 (required, number) - Усредненное значение пользовательских оценок варианта перевода
        + rates (required, object)
            + data (array)
        + created_at: 1489663450223 (required, number) - Время создания варианта перевода в формате Unix time
        + updated_at: 1489663450223 (required, number) - Время редактирования варианта перевода в формате Unix time

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Field 'body' is required."
                }
            ]
        }

## Вариант перевода [/materials/{material_id}/chunks/{chunk_id}/translations/{translation_id}]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала
    + chunk_id: 2 (required, number) - идентификатор чанка
    + translation_id: 5 (required, number) - идентификатор варианта перевода

### Получить вариант перевода [GET]

+ Response 200 (application/json)

    + Attributes (Translation)
        + rates
            + data (array, fixed-type)
                + (Rate)

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Translation was not found."
                }
            ]
        }

### Редактировать вариант перевода [PUT]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на редактирование варианта перевода
:::

::: note
#### Обработка параметров на сервере
Все указанные в запросе аттрибуты полностью заменяют соответствующие аттрибуты
в базе данных.
:::

+ Request (application/json)

    + Attributes (object)
        + body: Хей бро! (string) - Перевод чанка

+ Response 200 (application/json)

    + Attributes (Translation)
        + body: Хей бро! (string) - Перевод чанка
        + rates
            + data (array, fixed-type)
                + (Rate)

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Translator should exists."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Translation was not found."
                }
            ]
        }

### Удалить вариант перевода [DELETE]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на удаление варианта перевода
:::

+ Response 204 (application/json)

+ Response 401 (application/json)

        {
            "errors": [
                {
                    "title": "Unauthorized access.",
                    "detail": "You don't have rights to delete translation."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Translation was not found."
                }
            ]
        }

## Рейтинг [/materials/{material_id}/chunks/{chunk_id}/translations/{translation_id}/rate]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала
    + chunk_id: 2 (required, number) - идентификатор чанка
    + translation_id: 5 (required, number) - идентификатор варианта перевода

### Изменить рейтинг [POST]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на изменение рейтинга варианта перевода
:::

Атрибут | Тип | Описание
--- | --- | ---
value | Integer | Значение оценки. Может принимать значения `-1` / `1`

+ Request увеличение рейтинга (application/json)

    + Attributes
        + value: 1 (required, number)

+ Response 200 (application/json)

    + Attributes (Rate)
        + value: 1

+ Request уменьшение рейтинга (application/json)

    + Attributes
        + value: `-1` (required, number)

+ Response 200 (application/json)

    + Attributes (Rate)
        + value: `-1`

+ Response 401 (application/json)

        {
            "errors": [
                {
                    "title": "Unauthorized access.",
                    "detail": "You don't have rights to rate this translation."
                }
            ]
        }
