# Data Structures

## Material (object)

+ material_id: 213 (required, number) - Уникальный идентификатор материала
+ owner (required, Owner) - Владелец материала - институт, частное лицо, компания и т.д.
+ caption_original: Objects in Python (required, string) - Наименование материала на языке оригинала
+ caption_translated: Объекты в Python (string) - Переведенное на русский язык наименование материала
+ annotation_original: This lecture introduces Python (required, string) - Аннотация материала на языке оригинала
+ annotation_translated: В данной лекции вводятся понятия языка Python (string) - Переведенная на русский язык аннотация материала
+ state (required, State) - Текущее состояние материала
+ link: `https://ocw.mit.edu/computer-science/B8is52oxHBw.srt` (required, string) - Ссылка на оригинал
+ license (required, License) - Лицензия, по которой распространяется материал
+ tags (required, array) - Теги материала, включающие направление, категорию, положение в категории и прочее.

## MaterialTags (array)
+ (Tag)
    + tag_id: 32
    + name: course
    + display_name: курс
    + body (object)
        + original: Electrical Engineering and Computer Science
        + translated: Электротехника и вычислительная техника
+ (Tag)
    + tag_id: 12
    + name: course_position
    + display_name: номер в курсе
    + body: 1
+ (Tag)
    + tag_id: 2
    + name: category
    + display_name: наука
    + body: Информатика
+ (Tag)
    + tag_id: 54
    + name: subcategory
    + display_name: раздел науки
    + body: Программирование

+ (Tag)
    + tag_id: 82
    + name: author
    + display_name: автор
    + body (object)
        + original: Prof. John Guttag
        + translated: Профессор Джон Гуттаг

## Tag (object)
+ tag_id: 76 (required, number) - Уникальный идентификатор тега
+ name (required, string) - имя тега
+ display_name (required, string) - отображаемое имя тега
+ body (required, enum[string, object]) - значение тега

## License (object)

+ license_id: 7123 (required, number) - Уникальный идентификатор лицензии
+ name: `CC BY-NC-SA 4.0` (required, string) - Наименование лицензии
+ link: `https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode` (string) - Ссылка на положения лицензии

## Owner (object)

+ owner_id: 9876 (required, number) - Уникальный идентификатор правообладателя
+ caption_original: Massachusetts Institute of Technology (required, string) - Наименование правообладателя на языке оригинала
+ caption_translated: Массачусетский технологический институт (string) - Наименование правообладателя, переведенного на русский язык
+ short_original: MIT (required, string) - Сокращенное наименование правообладателя на языке оригинал
+ short_translated: МТИ (string) - Сокращенное наименование правообладателя, переведенное на русский язык
+ link: `http://web.mit.edu/` (string) - Ссылка на официальный ресурс в Интернете
+ icon: `http://web.mit.edu/files/images/homepage/default/mit_logo.gif?v=1487307612` (string) - Ссылка на иконку правообладателя

## State (object)

+ state_id: 34712 (required, number) - Уникальный идентификатор состояния
+ name: import (required, string) - Системное имя состояния (на английском языке, иначе slug)
+ display_name: Импорт (required, string) - Отображаемое наименование состояния

## Slice (object)

+ slice_id: 8712 (required, number) - Уникальный идентификатор слайса
+ material_id: 4567 (required, number) - Идентификатор материала, которому принадлежит слайс
+ material_position: 0 (required, number) - Позиция слайса в материале
+ type: text (required, string) - Тип слайса
+ translatable: true (required, boolean) - Слайс переводимый? Пример непереводимого слайса - иллюстрация без текста
+ body: Hey bro! (required, string) - Оригинальное значение слайса, в случае если значение нетекстовое (изображение, аудиозапись), то размещается ссылка на объект
+ translations (required, array) - Если слайс переводимый, то содержит массив переводов, иначе атрибут отсутствует

## Translation (object)

+ translation_id: 987 (required, number) - Уникальный идентификатор варианта перевода
+ slice_id: 8712 (required, number) - Идентификатор слайса, которому принадлежит вариант перевода
+ translator (required, User) - Автор (пользователь портала) варианта перевода
+ body: Хей бро! (required, string) - Перевод слайса
+ rating: 1 (required, number) - Усредненное значение пользовательских оценок варианта перевода
+ created_at (required, number) - Время создания варианта перевода в формате Unix time
+ updated_at (required, number) - Время редактирования варианта перевода в формате Unix time

## User (object)

+ user_id: 4567 (required, number) - Уникальный идентификатор пользователя
+ nickname: jonny (required, string) - Никнейм пользователя
+ avatar: `http://gravatar.com/jonny` (string) - Ссылка на аватар

## Comment (object)

+ comment_id: 123 (required, number) - Уникальный идентификатор комментария
+ slice_id (required, number) - Идентификатор слайса, которому принадлежит вариант перевода
+ commentator (required, User) - Автор комментария
+ body (required, string) - Текст комментария
+ parent_id (number) - Идентификатор родительского комментария

## Rate (object)

+ rate_id: 8762 (required, number) - Уникальный идентификатор оценки
+ rater (required, User) - Пользователь, поставивший оценку варианту перевода
+ value: 1 (required, number) - Значение оценки

# Group Типы данных
Раздел описывает основные типы данных для сервиса.

## Материал (Material)
С точки зрения переводов, редактуры и прочего **Материал** представляет собой
логически законченный, единый "кусок" данных, например:

* лекция
* субтитры
* раздаточные материалы

С точки зрения данного сервиса **Материал** представляет собой *метапакет*
хранящий фрагменты данных ([Слайсы](#header-слайс-(slice))), такие как:
фрагмент текста, формула, иллюстрация и т.д.

Атрибут | Тип | Описание
--- | --- | ---
material_id | Integer | Уникальный идентификатор материала.
owner | [Owner](#header-правообладатель-(owner)) | Владелец материала.
caption_original | String | Наименование материала на языке оригинала.
caption_translated | String | _Опционально._ Переведенное на русский язык наименование материала.
annotation_original | String | Аннотация материала на языке оригинала.
annotation_translated | String | _Опционально._ Переведенная на русский язык аннотация материала.
state | [State](#header-состояние-материала-(state)) | Состояния материала.
license | [License](#header-лицензия-(license)) | Лицензия, под которой распространяется материал.
tags | Array of [MaterialTag](#header-теги-материалов-(materialtag)) | _Опционально._ Теги материала.

## Теги материалов (MaterialTag)

Теги предназначены для дополнительной фильтрации материалов. Для каждой задачи
определяется свой набор тегов со своими полями в зависимости от семантики тега.

Например может существовать тег с одиночным значением, тогда в поле _body_
записывается непосредственно само значение в формате JSON. В случае более сложных
тегов, например с двумя полями — оригинальным и переведенным значениями в поле
_body_ должен быть записан JSON-объект с полям `original` (оригинальное значение),
`translated` (переведенное значение) и их значениями.

Атрибут | Тип | Описание
--- | --- | ---
tag_id | Integer | Уникальный идентификатор тега.
name | String | Имя тега (системное, латиницей без пробелов, иначе slug).
display_name | String | Отображаемое имя тега, может быть на любом языке.
body | JSON | Значение тега.

## Лицензия (License)
Каждый материал должен обладать своей лицензией. В большинстве случаев лицензия
указана в источнике материала, если лизцензия не указывается, то по-умолчанию
все материалы лицензируются по предопределенной системой лицензии, желательно
открытой, например `CC BY-NC-SA 4.0`.

Атрибут | Тип | Описание
--- | --- | ---
license_id | Integer | Уникальный идентификатор лицензии.
name | String | Наименование лицензии.
link | String | Ссылка на положения лицензии.

## Правообладатель (Owner)
Атрибут | Тип | Описание
--- | --- | ---
owner_id | String | Уникальный идентификатор правообладателя.
caption_original | String | Наименование правообладателя на языке оригинала.
caption_translated | String | _Опционально._ Наименование правообладателя, переведенного на русский язык.
short_original | String | Сокращенное наименование правообладателя на языке оригинал.
short_translated | String | _Опционально._ Сокращенное наименование правообладателя, переведенное на русский язык.
link | String | _Опционально._ Ссылка на официальный ресурс в Интернете.
icon | String | _Опционально._ Ссылка на иконку правообладателя.

## Состояние материала (State)
Текущее состояние материала. Может принимать следующие значения:

 1. `import` — Импорт
 2. `translate` — Перевод
 3. `edit` — Редактура
 4. `markup` — Верстка
 5. `published` — Публикация

Атрибут | Тип | Описание
--- | --- | ---
id | String | Уникальный идентификатор состояния.
name | String | Системное имя состояния (латиницей без пробелов, иначе slug).
display_name | String | Отображаемое наименование состояния.

## Слайс (Slice)
Слайс — минимальная, неделимая часть материала. Слайсы могут быть переводимые
и непереводимые и могут содержать следующие виды(типы) данных:

 - `text` — текст
 - `image` — изображение
 - `formulae` — формула (в формате LaTeX)
 - `audio` — аудиозапись
 - `video` — видеозапись

Атрибут | Тип | Описание
--- | --- | ---
slice_id | Integer | Уникальный идентификатор слайса.
material_id | Integer | Идентификатор материала, которому принадлежит слайс.
material_position | Integer | Позиция слайса в материале.
type | String | Тип слайса. См. в описании выше.
translatable | boolean | Слайс переводимый? Пример непереводимого слайса — иллюстрация без текста.
body | String | Оригинальное значение слайса, в случае если значение нетекстовое (изображение, аудиозапись), то размещается ссылка на объект
translations | Array of [Translation](#header-перевод-(translation)) | _Опционально._ Присутствует только в том случае, если слайс переводимый.

## Перевод (Translation)
Атрибут | Тип | Описание
--- | --- | ---
translation_id | Integer | Уникальный идентификатор варианта перевода.
slice_id | Integer | Идентификатор слайса, которому принадлежит вариант перевода.
translator | [User](#header-пользователь-(user)) | Автор (пользователь портала) варианта перевода.
body | String | Значение варианта перевода
comments | Array of [Comment](#header-комментарий-(comment)) | Комментарии к варианту перевода.
rating | Integer | Усредненное значение пользовательских оценок варианта перевода.
rates | Array of [Rate](#header-оценка-рейтинга-(rate)) | _Опционально._ Оценки варианта перевода пользователями.
created_at | Integer | Время создания варианта перевода в формате Unix time.
updated_at | Integer | Время редактирования варианта перевода в формате Unix time.

## Пользователь (User)
Атрибут | Тип | Описание
--- | --- | ---
user_id | String | Уникальный идентификатор пользователя.
nickname | String | Никнейм пользователя.
avatar | String | Ссылка на аватар.

## Комментарий (Comment)

::: note
Комментарии относятся к целому слайсу, не к какому-либо переводу, рейтингу,
чему либо другому, именно к слайсу.
:::

Атрибут | Тип | Описание
--- | --- | ---
comment_id | Integer | Уникальный идентификатор комментария.
slice_id | Integer | Идентификатор слайса, которому принадлежит вариант перевода.
commentator | [User](#header-пользователь-(user)) | Автор комментария.
body | String | Текст комментария.
parent_id | Integer | _Опционально._ Идентификатор родительского комментария

## Оценка рейтинга (Rate)
Пользовательская оценка варианта перевода, может принимать значение `+1`/`-1`.

Атрибут | Тип | Описание
--- | --- | ---
rate_id | String | Уникальный идентификатор оценки.
rater | [User](#header-пользователь-(user)) | Пользователь, поставивший оценку варианту перевода.
value | Integer | Значение оценки.
