FORMAT: 1A

# Junkyard

API для организации работы над оригинальными материалами, включая перевод
и редактирование.

# Data Structures

## Material (object)

+ id (required, number) - Уникальный идентификатор материала
+ owner (required, Owner) - Владелец материала - институт, частное лицо, компания и т.д.
+ category (required, Category) - Наука
+ subcategory (required, SubCategory) - Направление науки
+ course (Course) - Курс
+ course_position (number) - Порядковый номер материала в курсе
+ link: `https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-00sc-introduction-to-computer-science-and-programming-spring-2011/unit-1/lecture-5-objects-in-python/lecture-5-objects-in-python/B8is52oxHBw.srt` (required, string) - Ссылка на оригинал
+ caption_original: Objects in Python (required, string) - Наименование материала на языке оригинала
+ caption_translated: Объекты в Python (string) - Переведенное на русский язык наименование материала
+ annotation_original: This lecture introduces Python tuples, lists, and dictionaries, as well as the concept of mutability and how to avoid problems relating to it. (required, string) - Аннотация материала на языке оригинала
+ annotation_translated: В данной лекции вводятся понятия кортежей, списков и словарей в языке Python, а также рассматривается концепция мутабельности и способы решения связанных с ней проблем. (string) - Переведенная на русский язык аннотация материала
+ authors (required, array[Author]) - Список авторов материала
+ state (required, State) - Текущее состояние материала
+ license (required, License) - Лицензия, по которой распространяется материал

## License (object)

+ id (required, number) - Уникальный идентификатор лицензии
+ name: CC BY-NC-SA 4.0 (required, string) - Наименование лицензии
+ link: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode (string) - Ссылка на положения лицензии

## Owner (object)

+ id (required, number) - Уникальный идентификатор правообладателя
+ caption_original: Massachusetts Institute of Technology (required, string) - Наименование правообладателя на языке оригинала
+ caption_translated: Массачусетский технологический институт (string) - Наименование правообладателя, переведенного на русский язык
+ short_original: MIT (required, string) - Сокращенное наименование правообладателя на языке оригинал
+ short_translated: МТИ (string) - Сокращенное наименование правообладателя, переведенное на русский язык
+ link: http://web.mit.edu/ (string) - Ссылка на официальный ресурс в Интернете
+ icon: `http://web.mit.edu/files/images/homepage/default/mit_logo.gif?v=1487307612` (string) - Ссылка на иконку правообладателя

## Category (object)

+ id (required, number) - Уникальный идентификатор раздела науки
+ name: Информатика (required, string) - Наименование науки

## SubCategory (object)

+ id (required, number) - Уникальный идентификатор направления науки
+ caption: Программирование (required, string) - Наименование направления науки

## Course (object)

+ caption_original: Electrical Engineering and Computer Science (required, string) - Оригинальное наименование курса
+ caption_translated: Электротехника и вычислительная техника (string) - Переведенное на русский язык наименование курса

## Author (object)

+ id (required, number) - Уникальный идентификатор автора
+ name_original: Prof. John Guttag (required, string) - Имя автора на языке оригинала
+ name_translated: Профессор Джон Гуттаг (string) - Переведенное на русский язык имя автора

## State (object)

+ id (required, number) - Уникальный идентификатор состояния
+ name: import (required, string) - Системное имя состояния (на английском языке, иначе slug)
+ display_name: Импорт (required, string) - Отображаемое наименование состояния

## Slice (object)

+ id (required, number) - Уникальный идентификатор слайса
+ material_id (required, number) - Идентификатор материала, которому принадлежит слайс
+ material_position (required, number) - Позиция слайса в материале
+ type (required, string) - Тип слайса
+ translatable (required, boolean) - Слайс переводимый? Пример непереводимого слайса - иллюстрация без текста
+ original (required, string) - Оригинальное значение слайса, в случае если значение нетекстовое (изображение, аудиозапись), то размещается ссылка на объект
+ translations (array[Translation]) - Если слайс переводимый, то содержит массив переводов, иначе атрибут отсутствует

## Translation (object)

+ id (required, number) - Уникальный идентификатор варианта перевода
+ slice_id (required, number) - Идентификатор слайса, которому принадлежит вариант перевода
+ translator (required, User) - Автор (пользователь портала) варианта перевода
+ comments (array[Comment]) - Комментарии к варианту перевода
+ rating (required, number) - Усредненное значение пользовательских оценок варианта перевода
+ marks (array[Mark]) - Оценки варианта перевода пользователями
+ created_at (required, number) - Время создания варианта перевода в формате Unix time
+ updated_at (required, number) - Время редактирования варианта перевода в формате Unix time

## User (object)

+ id (number) - Уникальный идентификатор пользователя
+ nickname (string) - Никнейм пользователя
+ avatar (string) - Ссылка на аватар

## Comment (object)

+ id (required, number) - Уникальный идентификатор комментария
+ slice_id (required, number) - Идентификатор слайса, которому принадлежит вариант перевода
+ commentator (required, User) - Автор комментария
+ text (required, string) - Текст комментария
+ comments (array[Comment]) - Комментарии к варианту перевода, являющиеся ответами на текущий комментарий

## Mark (object)

+ id (required, number) - Уникальный идентификатор оценки
+ rater (required, User) - Пользователь, поставивший оценку варианту перевода
+ value (required, number) - Значение оценки

# Group Материалы

## Материалы [/materials]

### Список всех материалов [GET]

+ Response 200 (application/json)

    + Attributes (Material)

### Создать новый материал [POST]

+ Response 201 (application/json)

    + Attributes (Material)

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Owner is required."
                }
            ]
        }
