# Group Материалы
## Материалы [/materials]
### Список материалов [GET /materials{?page_size,page_number,order,direction,filter}]
+ Parameters
    + page_size: 10 (optional, number) - Количество возвращаемых материалов на одной "странице".
        + Default: `20`
    + page_number: 5 (optional, number) - Начиная с какой "страницы" возвращать материалы.
        + Default: `0`
    + direction: asc (optional, string) - Сортировка результатов.
        + Default: `desc`
    + order: `updated` (optional, string) - Сортировка материалов.
        + Default: `updated`
    + filter (optional, array) - Объект с фильтрами для материалов.

+ Response 200 (application/json)

    + Attributes (array)
        + (Material)
            + material_id: 123
            + tags (MaterialTags)
        + (Material)
            + material_id: 124
            + caption_original: Meet Elixir
            + caption_translated: Встречайте Elixir
            + annotation_original: Elixir language in common
            + annotation_translated: Общие понятия о языке Elixir
            + tags (MaterialTags)

### Создать материал [POST]
Материал может создаваться в полной форме и в сокращенной

::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на создание материалов
:::

Атрибут | Тип | Описание
--- | --- | ---
owner_id | Integer | Идентификатор правообладателя.
caption_original | String | Наименование материала на языке оригинала.
caption_translated | String | _Опционально._ Переведенное на русский язык наименование материала.
annotation_original | String | Аннотация материала на языке оригинала.
annotation_translated | String | _Опционально._ Переведенная на русский язык аннотация материала.
state_id | Integer | _Опционально._ Идентификатор состояния материала. _По-умолчанию ставится идентификатор, соответствующий состоянию `import`_
license_id | Integer | _Опционально._ Лицензия, под которой распространяется материал. _По-умолчанию ставится лицензия из настроек в системе._
tags | Array of [MaterialTag](#header-теги-материалов-(materialtag)) | _Опционально._ Теги материала. Могут передаваться списком из id, если они уже есть в базе данных, либо объектами, если их не существует.

+ Request полная форма (application/json)

    + Attributes (object)
        + owner_id: 9876 (required, number) - идентификатор владельца материала
        + state_id: 34712 (optional, number) - идентификатор состояния материала
        + caption_original: Objects in Python (required, string) - Наименование материала на языке оригинала
        + caption_translated: Объекты в Python (optional, string) - Переведенное на русский язык наименование материала
        + annotation_original: This lecture introduces Python (required, string) - Аннотация материала на языке оригинала
        + annotation_translated: В данной лекции вводятся понятия языка Python (optional, string) - Переведенная на русский язык аннотация материала
        + license_id: 7123 (optional, number) - идентификатор лицензии
        + tags: 1, 43, 23 (MaterialTags) - массив объектов типа Tag

+ Response 201 (application/json)

    + Attributes (Material)

+ Request сокращеная форма (application/json)

    + Attributes
        + owner_id: 9876 (required, number) - идентификатор владельца материала
        + caption_original: Objects in Python (required, string) - Наименование материала на языке оригинала
        + annotation_original: This lecture introduces Python (required, string) - Аннотация материала на языке оригинала

+ Response 201 (application/json)

    + Attributes (Material)
        + tags (array)
        + caption_translated (string)
        + annotation_translated (string)

+ Request с ошибками (application/json)

    + Attributes
        + caption_original: Objects in Python (required, string) - Наименование материала на языке оригинала
        + annotation_original: This lecture introduces Python (required, string) - Аннотация материала на языке оригинала

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Fiesd 'owner_id' is required."
                }
            ]
        }

## Материал [/materials/{material_id}]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала

### Получить материал [GET]

+ Response 200 (application/json)

    + Attributes (Material)

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Material was not found."
                }
            ]
        }

### Редактировать материал [POST]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на редактирование материалов
:::

+ Request (application/json)

    + Attributes (Material)

+ Response 200 (application/json)

    + Attributes (Material)

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Owner should exists."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Material was not found."
                }
            ]
        }

### Удалить материал [DELETE]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на удаление материалов
:::

+ Response 204 (application/json)

+ Response 401 (application/json)

        {
            "errors": [
                {
                    "title": "Unauthorized access.",
                    "detail": "You don't have rights to delete material."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Material was not found."
                }
            ]
        }
