# Group Материалы
## Материалы [/materials]
### Список материалов [GET]
Параметр | Тип | Обяз. | Описание
--- | --- | --- | ---
page_size | number | нет | Количество возвращаемых материалов на одной "странице". _По-умолчанию 20_
page_number | number | нет | Начиная с какой "страницы" возвращать материалы. _По-умолчанию 0_
order_by | string | нет | Сортировка материалов. _По-умолчанию created_at_
order_direction | string | нет | Сортировка в порядке убывания. _По-умолчанию desc_
filter | string | нет | Объект с фильтрами для материалов.

+ Response 200 (application/json)

    + Attributes (array[Material])

### Создать материал [POST]
Материал может создаваться в полной форме и в сокращенной

::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на создание материалов
:::

Атрибут | Тип | Описание
--- | --- | ---
owner_id | Integer | Идентификатор правообладателя.
caption_original | String | Наименование материала на языке оригинала.
caption_translated | String | _Опционально._ Переведенное на русский язык наименование материала.
annotation_original | String | Аннотация материала на языке оригинала.
annotation_translated | String | _Опционально._ Переведенная на русский язык аннотация материала.
state_id | Integer | _Опционально._ Идентификатор состояния материала. _По-умолчанию ставится `import`_
license_id | Integer | _Опционально._ Лицензия, под которой распространяется материал. _По-умолчанию ставится лицензия из настроек в системе._
tags | Array of [MaterialTag](#header-теги-материалов-(materialtag)) | _Опционально._ Теги материала.

+ Request полная форма (application/json)

    + Attributes (object)
        + owner: 9876 (required, number) - идентификатор владельца материала
        + state: 34712 (required) - идентификатор состояния материала
        + caption_original: Objects in Python (required, string) - Наименование материала на языке оригинала
        + caption_translated: Объекты в Python (string) - Переведенное на русский язык наименование материала
        + annotation_original: This lecture introduces Python (required, string) - Аннотация материала на языке оригинала
        + annotation_translated: В данной лекции вводятся понятия языка Python (string) - Переведенная на русский язык аннотация материала
        + license: 7123 (number) - идентификатор лицензии
        + tags (MaterialTags) - массив объектов типа Tag

+ Response 201 (application/json)

    + Attributes (Material)

+ Request сокращеная форма (application/json)

    + Body

            {
                "owner": "9876",
                "caption_original": "Objects in Python",
                "annotation_original": "This lecture introduces Python",
            }

+ Response 201 (application/json)

    + Attributes (Material)
        + tags (array)
        + caption_translated (string)
        + annotation_translated (string)

+ Request с ошибками (application/json)

    + Body

            {
                "caption_original": "Objects in Python",
                "annotation_original": "This lecture introduces Python",
            }

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Owner is required."
                }
            ]
        }

## Материал [/materials/{material_id}]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала

### Получить материал [GET]

+ Response 200 (application/json)

    + Attributes (Material)

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Material was not found."
                }
            ]
        }

### Редактировать материал [POST]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на редактирование материалов
:::

+ Request (application/json)

    + Attributes (Material)

+ Response 200 (application/json)

    + Attributes (Material)

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Owner should exists."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Material was not found."
                }
            ]
        }

### Удалить материал [DELETE]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на удаление материалов
:::

+ Response 204 (application/json)

+ Response 401 (application/json)

        {
            "errors": [
                {
                    "title": "Unauthorized access.",
                    "detail": "You don't have rights to delete material."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Material was not found."
                }
            ]
        }
