# Group Слайсы

## Слайсы [/materials/{material_id}/slices]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала

### Список всех слайсов материала [GET]

+ Response 200 (application/json)

    + Attributes (array[Slice])

### Создание нового слайса [POST]

+ Request

    + Attributes (Slice)

+ Response 201 (application/json)

    + Attributes (Slice)

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Original is required."
                }
            ]
        }
