# Group Слайсы

## Слайсы [/materials/{material_id}/slices]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала

### Список всех слайсов материала [GET]

+ Response 200 (application/json)

    + Attributes (array[Slice])
