# Group Слайсы
## Слайсы [/materials/{material_id}/slices]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала

### Список слайсов [GET]

+ Response 200 (application/json)

    + Attributes (array[Slice])

### Создать слайс [POST]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на создание слайсов
:::

Атрибут | Тип | Описание
--- | --- | ---
material_id | Integer | Идентификатор материала, которому принадлежит слайс.
material_position | Integer | Позиция слайса в материале.
type | String | Тип слайса. См. в описании выше.
translatable | boolean | Слайс переводимый? Пример непереводимого слайса — иллюстрация без текста.
body | String | Оригинальное значение слайса, в случае если значение нетекстовое (изображение, аудиозапись), то размещается ссылка на объект

+ Request

    + Attributes (Slice)

+ Response 201 (application/json)

    + Attributes (Slice)

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Original is required."
                }
            ]
        }

## Слайс [/materials/{material_id}/slices/{slice_id}]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала
    + slice_id: 2 (required, number) - идентификатор слайса

### Получить слайс [GET]

+ Response 200 (application/json)

    + Attributes (Slice)

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Material was not found."
                }
            ]
        }

### Редактировать слайс [PUT]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на редактирование слайсов
:::

::: note
#### Обработка параметров на сервере
Все указанные в запросе аттрибуты полностью заменяют соответствующие аттрибуты
в базе данных.
:::

+ Request

    + Attributes (Slice)

+ Response 200 (application/json)

    + Attributes (Slice)

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Original should exists."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Slice was not found."
                }
            ]
        }

### Удалить слайс [DELETE]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на удаление слайсов
:::

+ Response 200 (application/json)

+ Response 401 (application/json)

        {
            "errors": [
                {
                    "title": "Unauthorized access.",
                    "detail": "You don't have rights to delete slice."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Slice was not found."
                }
            ]
        }

## Комментарии [/materials/{material_id}/slices/{slice_id}/comments]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала
    + slice_id: 2 (required, number) - идентификатор слайса

### Список комментариев [GET]

+ Response 200 (application/json)

    + Attributes (array[Comment])

### Создать комментарий [POST]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на создание комментариев
:::

Атрибут | Тип | Описание
--- | --- | ---
slice_id | Integer | Идентификатор слайса, которому принадлежит вариант перевода.
commentator | Integer | Идентификатор автора комментария.
body | String | Текст комментария.
parent_id | Integer | _Опционально._ Идентификатор родительского комментария

+ Request (application/json)

    + Attributes (Comment)

+ Response 201 (application/json)

    + Attributes (Comment)

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Text is required."
                }
            ]
        }

+ Response 401 (application/json)

        {
            "errors": [
                {
                    "title": "Unauthorized access.",
                    "detail": "You don't have rights to comment this slice."
                }
            ]
        }

## Комментарий [/materials/{material_id}/slices/{slice_id}/comments/{comment_id}]

+ Parameters
    + material_id: 1 (required, number) - идентификатор материала
    + slice_id: 2 (required, number) - идентификатор слайса
    + comment_id: 10 (required, number) - идентификатор комментария

### Получить комментарий [GET]

+ Response 200 (application/json)

    + Attributes (Comment)

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Comment was not found."
                }
            ]
        }

### Редактировать комментарий [POST]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на редактирование комментариев
:::

+ Request (application/json)

    + Attributes (Comment)

+ Response 200 (application/json)

    + Attributes (Comment)

+ Response 400 (application/json)

        {
            "errors": [
                {
                    "title": "Invalid attribute.",
                    "detail": "Text should exists."
                }
            ]
        }

+ Response 401 (application/json)

        {
            "errors": [
                {
                    "title": "Unauthorized access.",
                    "detail": "You don't have rights to edit this comment."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Comment was not found."
                }
            ]
        }

### Удалить комментарий [DELETE]
::: warning
#### <i class="fa fa-warning"></i> Внимание
Пользователь должен обладать правами на удаление комментариев
:::

+ Response 204 (application/json)

+ Response 401 (application/json)

        {
            "errors": [
                {
                    "title": "Unauthorized access.",
                    "detail": "You don't have rights to delete this comment."
                }
            ]
        }

+ Response 404 (application/json)

        {
            "errors": [
                {
                    "title": "Entity not found.",
                    "detail": "Comment was not found."
                }
            ]
        }
